# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-06-26 13:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20170626_1249'),
    ]

    operations = [
        migrations.CreateModel(
            name='Portal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.CharField(max_length=4096)),
                ('lat', models.FloatField(default=0.0)),
                ('lng', models.FloatField(default=0.0)),
                ('order', models.IntegerField(default=-1)),
                ('title', models.CharField(default=b'', max_length=128)),
            ],
        ),
        migrations.AddField(
            model_name='mission',
            name='creator',
            field=models.CharField(default=b'', max_length=32),
        ),
        migrations.AddField(
            model_name='mission',
            name='desc',
            field=models.CharField(default=b'', max_length=1024),
        ),
        migrations.AddField(
            model_name='mission',
            name='faction',
            field=models.CharField(default=b'', max_length=8),
        ),
        migrations.AddField(
            model_name='mission',
            name='image',
            field=models.CharField(default=b'', max_length=256),
        ),
        migrations.AddField(
            model_name='mission',
            name='title',
            field=models.CharField(default=b'', max_length=128),
        ),
        migrations.AlterField(
            model_name='mission',
            name='data',
            field=models.CharField(max_length=4096),
        ),
        migrations.AlterField(
            model_name='mission',
            name='ref',
            field=models.CharField(default=b'', max_length=64),
        ),
    ]
