# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-06-26 13:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20170626_1342'),
    ]

    operations = [
        migrations.AddField(
            model_name='portal',
            name='mission',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.Mission'),
        ),
    ]
