# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-06-26 14:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_portal_mission'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='portal',
            name='data',
        ),
    ]
