# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-06-26 14:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_remove_portal_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='mission',
            name='_distance',
            field=models.IntegerField(default=-1),
        ),
        migrations.AddField(
            model_name='mission',
            name='_startLat',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='mission',
            name='_startLng',
            field=models.FloatField(default=0.0),
        ),
    ]
