# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-06-26 15:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20170626_1458'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portal',
            name='mission',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='portals', to='api.Mission'),
        ),
    ]
