# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-06-26 15:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20170626_1507'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mission',
            name='_distance',
            field=models.FloatField(default=0.0),
        ),
    ]
