# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-06-28 14:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_auto_20170628_1336'),
    ]

    operations = [
        migrations.AddField(
            model_name='mosaic',
            name='order',
            field=models.IntegerField(default=0),
        ),
    ]
