# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-06-28 14:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_mosaic_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mosaic',
            name='order',
        ),
        migrations.AddField(
            model_name='mission',
            name='order',
            field=models.IntegerField(default=0),
        ),
    ]
