# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-06-28 15:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_auto_20170628_1452'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mosaic',
            old_name='registered',
            new_name='registerer',
        ),
    ]
