# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-06-28 15:37
from __future__ import unicode_literals

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_auto_20170628_1528'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mosaic',
            name='ref',
            field=models.CharField(default=api.models._createRef, max_length=32, unique=True),
        ),
        migrations.AlterField(
            model_name='mosaic',
            name='status',
            field=models.CharField(default=b'active', max_length=64),
        ),
    ]
