# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-06-30 14:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_auto_20170629_1353'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mission',
            name='data',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='mission',
            name='desc',
            field=models.TextField(default=b''),
        ),
    ]
