# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-07-03 08:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_auto_20170630_1453'),
    ]

    operations = [
        migrations.AddField(
            model_name='mission',
            name='unavailable',
            field=models.BooleanField(default=False),
        ),
    ]
