# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-07-03 08:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_mission_unavailable'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mission',
            name='unavailable',
        ),
    ]
