# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-07-07 07:13
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_mosaic_region'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mosaic',
            name='registerer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mosaics', to=settings.AUTH_USER_MODEL),
        ),
    ]
