# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-07-18 12:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_auto_20170707_0713'),
    ]

    operations = [
        migrations.AddField(
            model_name='mosaic',
            name='rows',
            field=models.IntegerField(default=0),
        ),
    ]
