# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-07-18 12:09
from __future__ import unicode_literals

from django.db import migrations


def set_my_defaults(apps, schema_editor):
    Mosaic = apps.get_model('api', 'Mosaic')
    for mosaic in Mosaic.objects.all().iterator():
        mosaic.rows = (mosaic.count / mosaic.cols) + 1
        mosaic.save()
        
class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_auto_20170718_1203'),
    ]

    operations = [
        migrations.RunPython(set_my_defaults),
        migrations.RemoveField(
            model_name='mosaic',
            name='count',
        ),
    ]
