# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-09-04 15:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0025_remove_mosaic_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mission',
            name='ref',
            field=models.CharField(default=b'', max_length=64, unique=True),
        ),
    ]
