# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-09-15 09:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0027_searchresult'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mosaic',
            name='city',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='mosaic',
            name='country',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='mosaic',
            name='region',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
