# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-09-21 07:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0028_auto_20170915_0903'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mosaic',
            name='desc',
        ),
        migrations.RemoveField(
            model_name='mosaic',
            name='rows',
        ),
    ]
