# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-09-21 08:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0030_auto_20170921_0728'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='portal',
            name='mission',
        ),
        migrations.DeleteModel(
            name='SearchResult',
        ),
        migrations.RemoveField(
            model_name='mission',
            name='_distance',
        ),
        migrations.RemoveField(
            model_name='mission',
            name='_startLat',
        ),
        migrations.RemoveField(
            model_name='mission',
            name='_startLng',
        ),
        migrations.RemoveField(
            model_name='mission',
            name='creator',
        ),
        migrations.RemoveField(
            model_name='mission',
            name='desc',
        ),
        migrations.RemoveField(
            model_name='mission',
            name='faction',
        ),
        migrations.RemoveField(
            model_name='mission',
            name='image',
        ),
        migrations.RemoveField(
            model_name='mission',
            name='registerer',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='level',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='team',
        ),
        migrations.AlterField(
            model_name='mission',
            name='order',
            field=models.IntegerField(default=6),
        ),
        migrations.DeleteModel(
            name='Portal',
        ),
    ]
