# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-09-21 12:15
from __future__ import unicode_literals

from django.db import migrations, models

from api.models import *



def rebuild(apps, schema_editor):
    
    missions = Mission.objects.all()
    for m in missions:
        m.computeInternalData();
    
    mosaics = Mosaic.objects.all()
    for m in mosaics:
        m.computeInternalData();



class Migration(migrations.Migration):

    dependencies = [
        ('api', '0032_auto_20170921_1156'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mission',
            name='image',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='mission',
            name='title',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='mosaic',
            name='title',
            field=models.CharField(default=b'', max_length=256),
        ),
        
        migrations.RunPython(rebuild),
    ]
