# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-09-22 13:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0034_mosaic_creators'),
    ]

    operations = [
        migrations.AddField(
            model_name='mosaic',
            name='preview',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
    ]
