# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-09-25 15:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0035_mosaic_preview'),
    ]

    operations = [
        migrations.AddField(
            model_name='mission',
            name='name',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
