# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-09-22 08:22
from __future__ import unicode_literals

from django.db import migrations, models

from api.models import *



def update(apps, schema_editor):
    
	missions = Mission.objects.filter(mosaic__isnull=True, name__isnull=True)
	for m in missions:
        
		m.name = m.title
		m.name = m.name.replace('0', '')
		m.name = m.name.replace('1', '')
		m.name = m.name.replace('2', '')
		m.name = m.name.replace('3', '')
		m.name = m.name.replace('4', '')
		m.name = m.name.replace('5', '')
		m.name = m.name.replace('6', '')
		m.name = m.name.replace('7', '')
		m.name = m.name.replace('8', '')
		m.name = m.name.replace('9', '')
		m.name = m.name.replace('#', '')
		m.name = m.name.replace('０', '')
		m.name = m.name.replace('１', '')
		m.name = m.name.replace('２', '')
		m.name = m.name.replace('３', '')
		m.name = m.name.replace('４', '')
		m.name = m.name.replace('５', '')
		m.name = m.name.replace('６', '')
		m.name = m.name.replace('７', '')
		m.name = m.name.replace('８', '')
		m.name = m.name.replace('９', '')
		m.name = m.name.replace('①', '')
		m.name = m.name.replace('②', '')
		m.name = m.name.replace('③', '')
		m.name = m.name.replace('④', '')
		m.name = m.name.replace('⑤', '')
		m.name = m.name.replace('⑥', '')
		m.name = m.name.replace('.', '')
		m.name = m.name.replace('(', '')
		m.name = m.name.replace(')', '')
		m.name = m.name.replace('（', '')
		m.name = m.name.replace('）', '')
		m.name = m.name.replace('/', '')
		m.name = m.name.replace('[', '')
		m.name = m.name.replace(']', '')
		m.name = m.name.replace('【', '')
		m.name = m.name.replace('】', '')
		m.name = m.name.replace('-', '')
		m.name = m.name.replace('-', '')
		m.name = m.name.replace('－', '')
		m.name = m.name.replace('_', '')
		m.name = m.name.replace(':', '')
		m.name = m.name.replace('of ', '')
		m.name = m.name.replace(' of', '')
		m.name = m.name.replace('part ', '')
		m.name = m.name.replace(' part', '')
		m.name = m.name.replace('Part ', '')
		m.name = m.name.replace(' Part', '')
		m.name = m.name.replace('  ', ' ')
		m.name = m.name.replace('  ', ' ')
		m.name = m.name.replace('　', ' ')
		m.name = m.name.strip()
		
		m.save()



class Migration(migrations.Migration):

    dependencies = [
        ('api', '0036_mission_name'),
    ]

    operations = [
        migrations.RunPython(update),
    ]
