# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-10-02 16:53
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0037_mission_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('create_date', models.DateField(default=datetime.datetime.now)),
                ('update_date', models.DateField(default=datetime.datetime.now)),
            ],
        ),
        migrations.AddField(
            model_name='mosaic',
            name='completers',
            field=models.ManyToManyField(related_name='mosaics_completed', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='mosaic',
            name='lovers',
            field=models.ManyToManyField(related_name='mosaics_loved', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='comment',
            name='mosaic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='comments', to='api.Mosaic'),
        ),
        migrations.AddField(
            model_name='comment',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='comments', to=settings.AUTH_USER_MODEL),
        ),
    ]
