# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-10-05 09:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0039_profile_faction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mosaic',
            name='city',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='mosaic',
            name='region',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='mosaic',
            name='title',
            field=models.CharField(max_length=256),
        ),
    ]
