# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-10-05 09:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0040_auto_20171005_0939'),
    ]

    operations = [
        migrations.AddField(
            model_name='mission',
            name='admin',
            field=models.BooleanField(default=True),
        ),
    ]
