# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-11-02 09:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0042_auto_20171102_0914'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mission',
            name='registerer',
            field=models.TextField(blank=True, null=True),
        ),
    ]
