# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-11-09 10:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0044_auto_20171109_0829'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cities', to='api.Country'),
        ),
        migrations.AddField(
            model_name='city',
            name='region',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cities', to='api.Region'),
        ),
        migrations.AddField(
            model_name='region',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='regions', to='api.Country'),
        ),
        migrations.AlterField(
            model_name='city',
            name='name',
            field=models.CharField(max_length=512),
        ),
        migrations.AlterField(
            model_name='country',
            name='name',
            field=models.CharField(max_length=512),
        ),
        migrations.AlterField(
            model_name='region',
            name='name',
            field=models.CharField(max_length=512),
        ),
    ]
