# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-11-09 14:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0045_auto_20171109_1039'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mosaic',
            name='city',
        ),
        migrations.RemoveField(
            model_name='mosaic',
            name='country',
        ),
        migrations.RemoveField(
            model_name='mosaic',
            name='region',
        ),
        migrations.AlterField(
            model_name='mosaic',
            name='city_obj',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mosaics', to='api.City'),
        ),
        migrations.AlterField(
            model_name='mosaic',
            name='country_obj',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mosaics', to='api.Country'),
        ),
        migrations.AlterField(
            model_name='mosaic',
            name='region_obj',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mosaics', to='api.Region'),
        ),
    ]
