# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-11-09 18:45
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0047_auto_20171109_1425'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mosaic',
            name='completers',
            field=models.ManyToManyField(blank=True, null=True, related_name='mosaics_completed', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='mosaic',
            name='lovers',
            field=models.ManyToManyField(blank=True, null=True, related_name='mosaics_loved', to=settings.AUTH_USER_MODEL),
        ),
    ]
