# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-12-09 11:07
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0051_auto_20171129_1036'),
    ]

    operations = [
        migrations.CreateModel(
            name='Search',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.datetime.now)),
                ('city', models.TextField()),
                ('region', models.TextField()),
                ('country', models.TextField()),
                ('mosaic', models.BooleanField(default=False)),
            ],
        ),
    ]
