# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-12-18 08:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0052_search'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='search',
            name='mosaic',
        ),
        migrations.AddField(
            model_name='search',
            name='name',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='search',
            name='city',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='search',
            name='country',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='search',
            name='region',
            field=models.TextField(blank=True, null=True),
        ),
    ]
