# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2018-02-18 08:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0059_potential_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='potential',
            name='creator',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='potential',
            name='faction',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
