# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2018-03-13 08:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0062_auto_20180312_1950'),
    ]

    operations = [
        migrations.AddField(
            model_name='imcity',
            name='compare_name',
            field=models.CharField(default='', max_length=128),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='imcountry',
            name='compare_name',
            field=models.CharField(default='', max_length=128),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='imregion',
            name='compare_name',
            field=models.CharField(default='', max_length=128),
            preserve_default=False,
        ),
    ]
