# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2018-03-23 10:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0066_immosaic_excluded'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mosaic',
            old_name='portals',
            new_name='portal_count',
        ),
        migrations.RenameField(
            model_name='mosaic',
            old_name='uniques',
            new_name='unique_count',
        ),
        migrations.RenameField(
            model_name='potential',
            old_name='count',
            new_name='mission_count',
        ),
        migrations.RemoveField(
            model_name='immosaic',
            name='compare_name',
        ),
        migrations.RemoveField(
            model_name='mosaic',
            name='completers',
        ),
        migrations.RemoveField(
            model_name='mosaic',
            name='lovers',
        ),
        migrations.RemoveField(
            model_name='mosaic',
            name='preview',
        ),
        migrations.RemoveField(
            model_name='mosaic',
            name='status',
        ),
        migrations.RemoveField(
            model_name='mosaic',
            name='tags',
        ),
        migrations.RemoveField(
            model_name='mosaic',
            name='type',
        ),
        migrations.RemoveField(
            model_name='potential',
            name='creator',
        ),
        migrations.RemoveField(
            model_name='potential',
            name='faction',
        ),
    ]
