# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2018-03-27 07:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0068_auto_20180323_1453'),
    ]

    operations = [
        migrations.CreateModel(
            name='Waiting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256)),
                ('mission_refs', models.TextField()),
                ('mission_count', models.IntegerField()),
                ('mission_missing', models.TextField()),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='waitings', to='api.City')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='waitings', to='api.Country')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='waitings', to='api.Region')),
            ],
        ),
    ]
