# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2018-03-28 19:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0069_waiting'),
    ]

    operations = [
        migrations.AddField(
            model_name='mosaic',
            name='big_preview_url',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='mosaic',
            name='small_preview_url',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
