# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2018-04-02 11:49
from __future__ import unicode_literals

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0071_auto_20180402_1149'),
    ]

    operations = [
        migrations.AddField(
            model_name='immosaic',
            name='registered',
            field=models.BooleanField(default=False),
        ),
    ]
