# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2018-04-02 11:49
from __future__ import unicode_literals

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0075_auto_20180403_1149'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=256)),
                ('value', models.CharField(max_length=256)),
            ],
        ),
    ]
