# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2018-06-22 09:15
from __future__ import unicode_literals

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0082_auto_20180403_1149'),
    ]

    operations = [
        migrations.AlterField(
            model_name='waiting',
            name='ref',
            field=models.CharField(default=api.models._createRef, max_length=32, unique=True),
        ),
    ]
